### ISSUE TITLE
Inconsisten Segmentations in the Data

### ISSUE THREAD

**Issue by LinguList** [lexibank/ivanisuansu#4]
Segmentation was done by the author, but it turns out they are not consistent. Ideally, we would re-do them. Specifically vowel annotations  which are at times `oj` at times `o j` at times even `oi`.

**Comment by LinguList** [comment]
Sorry for not replying earlier. Ideally, yes, but I don't know when I find time. Should I try to fix it soon?

**Comment by LinguList** [comment]
Closing this issue now, as I fixed it for the time being. This can be released.

**Comment by MuffinLinwist** [comment]
thanks!
